services:
  api:
    image: api:latest
    container_name: api1
    ports:
      - "8000:8000"

    command: bash -c "python manage.py runserver 0.0.0.0:8000"

  web:
    image: front:latest
    container_name: front1
    ports:
      - "3000:3000"

